"""
Report Writer Tool — Student 4's Custom Tool

Writes the final investment research report as a structured Markdown
file to the ./reports/ directory. The Portfolio Strategist agent
uses this tool to produce the final deliverable.

The report includes:
    - Executive Summary
    - Technical Analysis Section
    - Sentiment Analysis Section
    - Fundamental Analysis Section
    - Final Buy/Hold/Sell Recommendation
    - Risk Factors
"""

from crewai.tools import tool
from typing import Any
from datetime import datetime
from pathlib import Path
from src.config import REPORTS_DIR
from src.utils.logger import get_logger, log_tool_call

logger = get_logger("Tool:ReportWriter")


@tool("Write Investment Report to File")
def write_report_to_file(ticker: str, report_content: str) -> str:
    """
    Write a formatted investment research report to a Markdown file.

    Creates a structured Markdown report in the ./reports/ directory
    with a timestamp and ticker symbol in the filename. The report
    is the final output of the Smart Investor Swarm pipeline.

    Args:
        ticker: The stock ticker symbol (e.g., 'AAPL').
        report_content: The full report text to write, including
            executive summary, analysis sections, and recommendation.

    Returns:
        A confirmation message with the file path where the report
        was saved, or an error message if writing fails.
    """
    ticker = ticker.strip().upper()
    logger.info(f"Writing investment report for {ticker}")

    try:
        # ─── Generate Filename ───────────────────────────────────
        timestamp: str = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename: str = f"{ticker}_investment_report_{timestamp}.md"
        filepath: Path = REPORTS_DIR / filename

        # ─── Build Report Header ─────────────────────────────────
        report_date: str = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        header: str = f"""# 📊 Investment Research Report: {ticker}

**Generated by:** Smart Investor Swarm (Multi-Agent System)
**Date:** {report_date}
**Disclaimer:** This report is generated by AI agents for educational purposes only.
It does not constitute financial advice. Always consult a qualified financial advisor.

---

"""

        # ─── Write to File ───────────────────────────────────────
        full_report: str = header + report_content

        filepath.write_text(full_report, encoding="utf-8")

        success_msg: str = (
            f"✅ Report successfully saved!\n"
            f"📁 File: {filepath.resolve()}\n"
            f"📄 Size: {filepath.stat().st_size:,} bytes\n"
            f"📅 Generated: {report_date}"
        )

        log_tool_call(
            logger,
            "write_report_to_file",
            {"ticker": ticker, "filepath": str(filepath)},
            success_msg,
        )
        logger.info(f"Report written to: {filepath.resolve()}")
        return success_msg

    except PermissionError:
        error_msg: str = (
            f"Permission denied: Cannot write to '{REPORTS_DIR}'. "
            "Please check directory permissions."
        )
        logger.error(error_msg)
        return error_msg
    except Exception as e:
        error_msg = f"Error writing report for '{ticker}': {str(e)}"
        logger.error(error_msg)
        return error_msg
